export const carUsageOptions = [
  {
    title: "Social use only",
    description:
      "Personal use such as shopping or visiting friends and family.",
  },
  {
    title: "Social and commuting",
    description:
      "Personal use and driving to and from a single place of work or study.",
  },
  {
    title: "Social, commuting and business",
    description:
      "You drive to various locations for work. You can also add other drivers who use this car for business.",
  },
];

export const otherVehiclesOptions = [
  "Own another car or van",
  "Have use of another car",
  "Company car (including personal use)",
  "Company car (excluding personal use)",
];

export const additionalQualificationsOptions = [
  "AA Proficiency",
  "Institute of Advanced Motorists",
  "Pass Plus",
];

export const monthOptions = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const yearOptions = Array.from({ length: 50 }, (_, i) => {
  const year = new Date().getFullYear() - i;
  return year.toString();
});

export const licenseHeldOptions = [
  "0-1 years",
  "2 years",
  "3 years",
  "4 years",
  "5 years",
  "6 years",
  "7 years",
  "8 years",
  "9 years",
  "10 years",
  "11 years",
  "12 years",
  "13 years",
  "14 years",
  "15+ years",
];

export const ncbOptions = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "15+",
];

export const keepingCarDuringNightOptions = [
  "Drive",
  "Street outside home",
  "Locked garage",
  "Street away from home",
  "Public car park",
  "Work car park",
  "Private property",
];

export const keepingCarDuringDayOptions = [
  "At home",
  "Office or factory car park",
  "Open public car park",
  "Secure public car park",
  "Street away from home",
];
export const employmentStatusOptions = [
  "Self-Employed",
  "Employed",
  "Unemployed",
  "Retired",
  "Student",
];

export const voluntaryExcessOptions = [
  "£0",
  "£100",
  "£250",
  "£500",
  "£750",
  "£1000",
];

export const industryOptions = [
  "Growing of cereals and leguminous crops",
  "Growing of cereals and leguminous crops (specialised)",
  "Growing of rice",
  "Growing of rice (specialised)",
  "Growing of vegetables and melons, roots and tubers",
  "Growing of vegetables and melons, roots and tubers (specialised)",
  "Growing of sugar cane",
  "Growing of sugar cane (specialised)",
  "Growing of tobacco",
  "Growing of tobacco (specialised)",
  "Growing of fibre crops",
  "Growing of fibre crops (specialised)",
  "Growing of other non-perennial crops",
  "Growing of other non-perennial crops (specialised)",
  "Growing of grapes",
  "Growing of grapes (specialised)",
  "Growing of tropical and subtropical fruits",
  "Growing of tropical and subtropical fruits (specialised)",
  "Growing of citrus fruits",
  "Growing of citrus fruits (specialised)",
  "Growing of pome fruits and stone fruits",
  "Growing of pome fruits and stone fruits (specialised)",
  "Growing of other tree and bush fruits and nuts",
  "Growing of other tree and bush fruits and nuts (specialised)",
  "Growing of oleaginous fruits",
  "Growing of oleaginous fruits (specialised)",
  "Growing of beverage crops",
  "Growing of beverage crops (specialised)",
  "Growing of spices, aromatic, drug and pharmaceutical crops",
  "Growing of spices, aromatic, drug and pharmaceutical crops (specialised)",
  "Growing of other perennial crops",
  "Growing of other perennial crops (specialised)",
  "Plant propagation",
  "Plant propagation (specialised)",
  "Raising of dairy cattle",
  "Raising of dairy cattle (specialised)",
  "Raising of other cattle and buffaloes",
  "Raising of other cattle and buffaloes (specialised)",
  "Raising of horses and other equines",
  "Raising of horses and other equines (specialised)",
  "Raising of camels and camelids",
  "Raising of camels and camelids (specialised)",
  "Raising of sheep and goats",
  "Raising of sheep and goats (specialised)",
  "Raising of swine/pigs",
  "Raising of swine/pigs (specialised)",
  "Raising of poultry",
  "Raising of poultry (specialised)",
  "Raising of other animals",
  "Raising of other animals (specialised)",
  "Mixed farming",
  "Mixed farming (specialised)",
  "Support activities for crop production",
  "Support activities for crop production (specialised)",
  "Support activities for animal production",
  "Support activities for animal production (specialised)",
  "Post-harvest crop activities",
  "Post-harvest crop activities (specialised)",
  "Seed processing for propagation",
  "Seed processing for propagation (specialised)",
  "Hunting, trapping and related service activities",
  "Hunting, trapping and related service activities (specialised)",
  "Silviculture and other forestry activities",
  "Silviculture and other forestry activities (specialised)",
  "Logging",
  "Logging (specialised)",
  "Gathering of wild growing non-wood products",
  "Gathering of wild growing non-wood products (specialised)",
  "Support services to forestry",
  "Support services to forestry (specialised)",
  "Fishing",
  "Fishing (specialised)",
  "Marine fishing",
  "Marine fishing (specialised)",
  "Freshwater fishing",
  "Freshwater fishing (specialised)",
  "Aquaculture",
  "Aquaculture (specialised)",
  "Mining of coal and lignite",
  "Mining of coal and lignite (specialised)",
  "Extraction of crude petroleum",
  "Extraction of crude petroleum (specialised)",
  "Extraction of natural gas",
  "Extraction of natural gas (specialised)",
  "Mining of iron ores",
  "Mining of iron ores (specialised)",
  "Mining of non-ferrous metal ores",
  "Mining of non-ferrous metal ores (specialised)",
  "Other mining and quarrying n.e.c.",
  "Other mining and quarrying n.e.c. (specialised)",
  "Support activities for petroleum and natural gas extraction",
  "Support activities for petroleum and natural gas extraction (specialised)",
  "Manufacture of food products",
  "Manufacture of food products (specialised)",
  "Manufacture of beverages",
  "Manufacture of beverages (specialised)",
  "Manufacture of tobacco products",
  "Manufacture of tobacco products (specialised)",
  "Manufacture of textiles",
  "Manufacture of textiles (specialised)",
  "Manufacture of wearing apparel",
  "Manufacture of wearing apparel (specialised)",
  "Manufacture of leather and related products",
  "Manufacture of leather and related products (specialised)",
  "Manufacture of wood and products of wood and cork",
  "Manufacture of wood and products of wood and cork (specialised)",
  "Manufacture of paper and paper products",
  "Manufacture of paper and paper products (specialised)",
  "Printing and reproduction of recorded media",
  "Printing and reproduction of recorded media (specialised)",
  "Manufacture of coke and refined petroleum products",
  "Manufacture of coke and refined petroleum products (specialised)",
  "Manufacture of chemicals and chemical products",
  "Manufacture of chemicals and chemical products (specialised)",
  "Manufacture of pharmaceuticals and medicinal products",
  "Manufacture of pharmaceuticals and medicinal products (specialised)",
  "Manufacture of rubber and plastic products",
  "Manufacture of rubber and plastic products (specialised)",
  "Manufacture of other non-metallic mineral products",
  "Manufacture of other non-metallic mineral products (specialised)",
  "Manufacture of basic metals",
  "Manufacture of basic metals (specialised)",
  "Manufacture of fabricated metal products",
  "Manufacture of fabricated metal products (specialised)",
  "Manufacture of computer, electronic and optical products",
  "Manufacture of computer, electronic and optical products (specialised)",
  "Manufacture of electrical equipment",
  "Manufacture of electrical equipment (specialised)",
  "Manufacture of machinery and equipment",
  "Manufacture of machinery and equipment (specialised)",
  "Manufacture of motor vehicles, trailers and semi-trailers",
  "Manufacture of motor vehicles, trailers and semi-trailers (specialised)",
  "Manufacture of other transport equipment",
  "Manufacture of other transport equipment (specialised)",
  "Manufacture of furniture",
  "Manufacture of furniture (specialised)",
  "Other manufacturing",
  "Other manufacturing (specialised)",
  "Repair and installation of machinery and equipment",
  "Repair and installation of machinery and equipment (specialised)",
  "Electric power generation, transmission and distribution",
  "Electric power generation, transmission and distribution (specialised)",
  "Manufacture of gas; distribution of gaseous fuels",
  "Manufacture of gas; distribution of gaseous fuels (specialised)",
  "Steam and air conditioning supply",
  "Steam and air conditioning supply (specialised)",
  "Water collection, treatment and supply",
  "Water collection, treatment and supply (specialised)",
  "Sewerage",
  "Sewerage (specialised)",
  "Waste collection",
  "Waste collection (specialised)",
  "Waste treatment and disposal",
  "Waste treatment and disposal (specialised)",
  "Materials recovery",
  "Materials recovery (specialised)",
  "Remediation activities and other waste management services",
  "Remediation activities and other waste management services (specialised)",
  "Construction of buildings",
  "Construction of buildings (specialised)",
  "Civil engineering",
  "Civil engineering (specialised)",
  "Specialised construction activities",
  "Specialised construction activities (specialised)",
  "Wholesale and retail trade and repair of motor vehicles and motorcycles",
  "Wholesale and retail trade and repair of motor vehicles and motorcycles (specialised)",
  "Wholesale trade, except of motor vehicles and motorcycles",
  "Wholesale trade, except of motor vehicles and motorcycles (specialised)",
  "Retail trade, except of motor vehicles and motorcycles",
  "Retail trade, except of motor vehicles and motorcycles (specialised)",
  "Land transport and transport via pipelines",
  "Land transport and transport via pipelines (specialised)",
  "Water transport",
  "Water transport (specialised)",
  "Air transport",
  "Air transport (specialised)",
  "Warehousing and support activities for transportation",
  "Warehousing and support activities for transportation (specialised)",
  "Postal and courier activities",
  "Postal and courier activities (specialised)",
  "Accommodation",
  "Accommodation (specialised)",
  "Food and beverage service activities",
  "Food and beverage service activities (specialised)",
  "Publishing activities",
  "Publishing activities (specialised)",
  "Motion picture, video and television programme production, sound recording and music publishing",
  "Motion picture, video and television programme production, sound recording and music publishing (specialised)",
  "Programming and broadcasting activities",
  "Programming and broadcasting activities (specialised)",
  "Telecommunications",
  "Telecommunications (specialised)",
  "Computer programming, consultancy and related activities",
  "Computer programming, consultancy and related activities (specialised)",
  "Information service activities",
  "Information service activities (specialised)",
  "Financial service activities, except insurance and pension funding",
  "Financial service activities, except insurance and pension funding (specialised)",
  "Insurance, reinsurance and pension funding, except compulsory social security",
  "Insurance, reinsurance and pension funding, except compulsory social security (specialised)",
  "Activities auxiliary to financial services and insurance",
  "Activities auxiliary to financial services and insurance (specialised)",
  "Real estate activities",
  "Real estate activities (specialised)",
  "Legal and accounting activities",
  "Legal and accounting activities (specialised)",
  "Activities of head offices; management consultancy",
  "Activities of head offices; management consultancy (specialised)",
  "Architectural and engineering activities; technical testing and analysis",
  "Architectural and engineering activities; technical testing and analysis (specialised)",
  "Scientific research and development",
  "Scientific research and development (specialised)",
  "Advertising and market research",
  "Advertising and market research (specialised)",
  "Other professional, scientific and technical activities",
  "Other professional, scientific and technical activities (specialised)",
  "Veterinary activities",
  "Veterinary activities (specialised)",
  "Rental and leasing activities",
  "Rental and leasing activities (specialised)",
  "Employment activities",
  "Employment activities (specialised)",
  "Travel agency, tour operator and other reservation service activities",
  "Travel agency, tour operator and other reservation service activities (specialised)",
  "Security and investigation activities",
  "Security and investigation activities (specialised)",
  "Services to buildings and landscape activities",
  "Services to buildings and landscape activities (specialised)",
  "Office administrative, office support and other business support activities",
  "Office administrative, office support and other business support activities (specialised)",
  "Public administration and defence; compulsory social security",
  "Public administration and defence; compulsory social security (specialised)",
  "Education",
  "Education (specialised)",
  "Human health activities",
  "Human health activities (specialised)",
  "Residential care activities",
  "Residential care activities (specialised)",
  "Social work activities without accommodation",
  "Social work activities without accommodation (specialised)",
  "Creative, arts and entertainment activities",
  "Creative, arts and entertainment activities (specialised)",
  "Libraries, archives, museums and other cultural activities",
  "Libraries, archives, museums and other cultural activities (specialised)",
  "Gambling and betting activities",
  "Gambling and betting activities (specialised)",
  "Sports activities and amusement and recreation activities",
  "Sports activities and amusement and recreation activities (specialised)",
  "Activities of membership organisations",
  "Activities of membership organisations (specialised)",
  "Repair of computers and personal and household goods",
  "Repair of computers and personal and household goods (specialised)",
  "Other personal service activities",
  "Other personal service activities (specialised)",
  "Activities of households as employers of domestic personnel",
  "Activities of households as employers of domestic personnel (specialised)",
  "Undifferentiated goods- and services-producing activities of households for own use",
  "Undifferentiated goods- and services-producing activities of households for own use (specialised)",
  "Activities of extraterritorial organisations and bodies",
  "Activities of extraterritorial organisations and bodies (specialised)",
];

export const occupationOptions = [
  "Accountant",
  "Accounting Assistant",
  "Administrative Assistant",
  "Administrator",
  "Auditor",
  "Bookkeeper",
  "Business Analyst",
  "Chief Executive",
  "Company Secretary",
  "Data Entry Clerk",
  "Executive Assistant",
  "Finance Manager",
  "Financial Advisor",
  "Office Manager",
  "Operations Manager",
  "Payroll Clerk",
  "Project Manager",
  "Receptionist",
  "Secretary",
  "Tax Advisor",
  "Treasurer",
  "App Developer",
  "Backend Developer",
  "Blockchain Developer",
  "Cloud Engineer",
  "Computer Programmer",
  "Cyber Security Analyst",
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
  "Database Administrator",
  "DevOps Engineer",
  "Front End Developer",
  "Full Stack Developer",
  "Game Designer",
  "Game Developer",
  "IT Consultant",
  "IT Manager",
  "Network Engineer",
  "Software Engineer",
  "System Administrator",
  "Technical Support Specialist",
  "UX Designer",
  "UI Designer",
  "Web Developer",
  "Web Designer",
  "Care Assistant",
  "Dental Nurse",
  "Dentist",
  "Doctor",
  "GP",
  "Healthcare Assistant",
  "Hospital Porter",
  "Medical Laboratory Assistant",
  "Medical Secretary",
  "Midwife",
  "Nurse",
  "Occupational Therapist",
  "Optician",
  "Paramedic",
  "Pharmacist",
  "Pharmacy Technician",
  "Physiotherapist",
  "Radiographer",
  "Surgeon",
  "Veterinary Nurse",
  "Veterinary Surgeon",
  "Academic Researcher",
  "College Lecturer",
  "Nursery Assistant",
  "Primary School Teacher",
  "Professor",
  "School Administrator",
  "Secondary School Teacher",
  "Special Needs Teacher",
  "Teaching Assistant",
  "Tutor",
  "Bricklayer",
  "Builder",
  "Carpenter",
  "Decorator",
  "Electrician",
  "Floor Fitter",
  "Joiner",
  "Labourer",
  "Painter",
  "Plasterer",
  "Plumber",
  "Roofer",
  "Scaffolder",
  "Site Manager",
  "Surveyor",
  "Tiler",
  "Welder",
  "Barista",
  "Butcher",
  "Cashier",
  "Customer Service Advisor",
  "Customer Support Agent",
  "Delivery Driver",
  "Retail Assistant",
  "Retail Manager",
  "Sales Assistant",
  "Shop Assistant",
  "Store Manager",
  "Supermarket Assistant",
  "Warehouse Operative",
  "Bus Driver",
  "Cab Driver",
  "Courier",
  "Forklift Operator",
  "HGV Driver",
  "Logistics Coordinator",
  "Pilot",
  "Taxi Driver",
  "Train Conductor",
  "Train Driver",
  "Transport Manager",
  "Actor",
  "Animator",
  "Art Director",
  "Artist",
  "Blogger",
  "Camera Operator",
  "Composer",
  "Copywriter",
  "Editor",
  "Fashion Designer",
  "Film Director",
  "Graphic Designer",
  "Illustrator",
  "Journalist",
  "Marketing Executive",
  "Marketing Manager",
  "Musician",
  "Photographer",
  "PR Manager",
  "Social Media Manager",
  "Video Editor",
  "Writer",
  "Barrister",
  "Civil Servant",
  "Court Clerk",
  "Firefighter",
  "Immigration Officer",
  "Judge",
  "Lawyer",
  "Legal Assistant",
  "Legal Secretary",
  "Paralegal",
  "Police Officer",
  "Probation Officer",
  "Solicitor",
  "Bar Manager",
  "Bartender",
  "Chef",
  "Concierge",
  "Event Planner",
  "Hotel Manager",
  "Housekeeper",
  "Kitchen Assistant",
  "Restaurant Manager",
  "Tour Guide",
  "Travel Agent",
  "Waiter",
  "Waitress",
  "Architect",
  "Biochemist",
  "Biologist",
  "Biomedical Scientist",
  "Chemical Engineer",
  "Chemist",
  "Civil Engineer",
  "Electrical Engineer",
  "Environmental Scientist",
  "Geologist",
  "Lab Technician",
  "Marine Biologist",
  "Mechanical Engineer",
  "Microbiologist",
  "Physicist",
  "Research Scientist",
  "Structural Engineer",
  "Agricultural Worker",
  "Farm Manager",
  "Farmer",
  "Fisherman",
  "Forest Ranger",
  "Gardener",
  "Greenkeeper",
  "Groundskeeper",
  "Horticulturist",
  "Landscape Gardener",
  "Tree Surgeon",
  "Athlete",
  "Coach",
  "Fitness Instructor",
  "Gym Manager",
  "Lifeguard",
  "Personal Trainer",
  "Sports Therapist",
  "Consultant",
  "Entrepreneur",
  "Freelancer",
  "Investor",
  "Self Employed",
  "Student",
  "Retired",
  "Unemployed",
];
