// This file contains the sorted options for occupation and industry
// Generated for alphabetical ordering

export const industryOptions = [
  "Accommodation",
  "Accommodation (specialised)",
  "Activities auxiliary to financial services and insurance",
  "Activities auxiliary to financial services and insurance (specialised)",
  "Activities of extraterritorial organisations and bodies",
  "Activities of extraterritorial organisations and bodies (specialised)",
  "Activities of head offices; management consultancy",
  "Activities of head offices; management consultancy (specialised)",
  "Activities of households as employers of domestic personnel",
  "Activities of households as employers of domestic personnel (specialised)",
  "Activities of membership organisations",
  "Activities of membership organisations (specialised)",
  "Advertising and market research",
  "Advertising and market research (specialised)",
  "Air transport",
  "Air transport (specialised)",
  "Aquaculture",
  "Aquaculture (specialised)",
  "Architectural and engineering activities; technical testing and analysis",
  "Architectural and engineering activities; technical testing and analysis (specialised)",
  "Civil engineering",
  "Civil engineering (specialised)",
  "Computer programming, consultancy and related activities",
  "Computer programming, consultancy and related activities (specialised)",
  "Construction of buildings",
  "Construction of buildings (specialised)",
  "Creative, arts and entertainment activities",
  "Creative, arts and entertainment activities (specialised)",
  "Education",
  "Education (specialised)",
  "Electric power generation, transmission and distribution",
  "Electric power generation, transmission and distribution (specialised)",
  "Employment activities",
  "Employment activities (specialised)",
  "Extraction of crude petroleum",
  "Extraction of crude petroleum (specialised)",
  "Extraction of natural gas",
  "Extraction of natural gas (specialised)",
  "Financial service activities, except insurance and pension funding",
  "Financial service activities, except insurance and pension funding (specialised)",
  "Fishing",
  "Fishing (specialised)",
  "Food and beverage service activities",
  "Food and beverage service activities (specialised)",
  "Freshwater fishing",
  "Freshwater fishing (specialised)",
  "Gambling and betting activities",
  "Gambling and betting activities (specialised)",
  "Gathering of wild growing non-wood products",
  "Gathering of wild growing non-wood products (specialised)",
  "Growing of beverage crops",
  "Growing of beverage crops (specialised)",
  "Growing of cereals and leguminous crops",
  "Growing of cereals and leguminous crops (specialised)",
  "Growing of citrus fruits",
  "Growing of citrus fruits (specialised)",
  "Growing of fibre crops",
  "Growing of fibre crops (specialised)",
  "Growing of grapes",
  "Growing of grapes (specialised)",
  "Growing of oleaginous fruits",
  "Growing of oleaginous fruits (specialised)",
  "Growing of other non-perennial crops",
  "Growing of other non-perennial crops (specialised)",
  "Growing of other perennial crops",
  "Growing of other perennial crops (specialised)",
  "Growing of other tree and bush fruits and nuts",
  "Growing of other tree and bush fruits and nuts (specialised)",
  "Growing of pome fruits and stone fruits",
  "Growing of pome fruits and stone fruits (specialised)",
  "Growing of rice",
  "Growing of rice (specialised)",
  "Growing of spices, aromatic, drug and pharmaceutical crops",
  "Growing of spices, aromatic, drug and pharmaceutical crops (specialised)",
  "Growing of sugar cane",
  "Growing of sugar cane (specialised)",
  "Growing of tobacco",
  "Growing of tobacco (specialised)",
  "Growing of tropical and subtropical fruits",
  "Growing of tropical and subtropical fruits (specialised)",
  "Growing of vegetables and melons, roots and tubers",
  "Growing of vegetables and melons, roots and tubers (specialised)",
  "Hunting, trapping and related service activities",
  "Hunting, trapping and related service activities (specialised)",
  "Human health activities",
  "Human health activities (specialised)",
  "Information service activities",
  "Information service activities (specialised)",
  "Insurance, reinsurance and pension funding, except compulsory social security",
  "Insurance, reinsurance and pension funding, except compulsory social security (specialised)",
  "Land transport and transport via pipelines",
  "Land transport and transport via pipelines (specialised)",
  "Legal and accounting activities",
  "Legal and accounting activities (specialised)",
  "Libraries, archives, museums and other cultural activities",
  "Libraries, archives, museums and other cultural activities (specialised)",
  "Logging",
  "Logging (specialised)",
  "Manufacture of basic metals",
  "Manufacture of basic metals (specialised)",
  "Manufacture of beverages",
  "Manufacture of beverages (specialised)",
  "Manufacture of chemical and chemical products",
  "Manufacture of chemicals and chemical products (specialised)",
  "Manufacture of coke and refined petroleum products",
  "Manufacture of coke and refined petroleum products (specialised)",
  "Manufacture of computer, electronic and optical products",
  "Manufacture of computer, electronic and optical products (specialised)",
  "Manufacture of electrical equipment",
  "Manufacture of electrical equipment (specialised)",
  "Manufacture of fabricated metal products",
  "Manufacture of fabricated metal products (specialised)",
  "Manufacture of food products",
  "Manufacture of food products (specialised)",
  "Manufacture of furniture",
  "Manufacture of furniture (specialised)",
  "Manufacture of leather and related products",
  "Manufacture of leather and related products (specialised)",
  "Manufacture of machinery and equipment",
  "Manufacture of machinery and equipment (specialised)",
  "Manufacture of motor vehicles, trailers and semi-trailers",
  "Manufacture of motor vehicles, trailers and semi-trailers (specialised)",
  "Manufacture of other non-metallic mineral products",
  "Manufacture of other non-metallic mineral products (specialised)",
  "Manufacture of other transport equipment",
  "Manufacture of other transport equipment (specialised)",
  "Manufacture of paper and paper products",
  "Manufacture of paper and paper products (specialised)",
  "Manufacture of pharmaceuticals and medicinal products",
  "Manufacture of pharmaceuticals and medicinal products (specialised)",
  "Manufacture of rubber and plastic products",
  "Manufacture of rubber and plastic products (specialised)",
  "Manufacture of textiles",
  "Manufacture of textiles (specialised)",
  "Manufacture of tobacco products",
  "Manufacture of tobacco products (specialised)",
  "Manufacture of wearing apparel",
  "Manufacture of wearing apparel (specialised)",
  "Manufacture of wood and products of wood and cork",
  "Manufacture of wood and products of wood and cork (specialised)",
  "Manufacture of gas; distribution of gaseous fuels",
  "Manufacture of gas; distribution of gaseous fuels (specialised)",
  "Marine fishing",
  "Marine fishing (specialised)",
  "Materials recovery",
  "Materials recovery (specialised)",
  "Mining of coal and lignite",
  "Mining of coal and lignite (specialised)",
  "Mining of iron ores",
  "Mining of iron ores (specialised)",
  "Mining of non-ferrous metal ores",
  "Mining of non-ferrous metal ores (specialised)",
  "Mixed farming",
  "Mixed farming (specialised)",
  "Motion picture, video and television programme production, sound recording and music publishing",
  "Motion picture, video and television programme production, sound recording and music publishing (specialised)",
  "Other manufacturing",
  "Other manufacturing (specialised)",
  "Other mining and quarrying n.e.c.",
  "Other mining and quarrying n.e.c. (specialised)",
  "Other professional, scientific and technical activities",
  "Other professional, scientific and technical activities (specialised)",
  "Office administrative, office support and other business support activities",
  "Office administrative, office support and other business support activities (specialised)",
  "Plant propagation",
  "Plant propagation (specialised)",
  "Post-harvest crop activities",
  "Post-harvest crop activities (specialised)",
  "Postal and courier activities",
  "Postal and courier activities (specialised)",
  "Programming and broadcasting activities",
  "Programming and broadcasting activities (specialised)",
  "Public administration and defence; compulsory social security",
  "Public administration and defence; compulsory social security (specialised)",
  "Publishing activities",
  "Publishing activities (specialised)",
  "Raising of camels and camelids",
  "Raising of camels and camelids (specialised)",
  "Raising of dairy cattle",
  "Raising of dairy cattle (specialised)",
  "Raising of horses and other equines",
  "Raising of horses and other equines (specialised)",
  "Raising of other animals",
  "Raising of other animals (specialised)",
  "Raising of other cattle and buffaloes",
  "Raising of other cattle and buffaloes (specialised)",
  "Raising of poultry",
  "Raising of poultry (specialised)",
  "Raising of sheep and goats",
  "Raising of sheep and goats (specialised)",
  "Raising of swine/pigs",
  "Raising of swine/pigs (specialised)",
  "Real estate activities",
  "Real estate activities (specialised)",
  "Remediation activities and other waste management services",
  "Remediation activities and other waste management services (specialised)",
  "Rental and leasing activities",
  "Rental and leasing activities (specialised)",
  "Repair and installation of machinery and equipment",
  "Repair and installation of machinery and equipment (specialised)",
  "Repair of computers and personal and household goods",
  "Repair of computers and personal and household goods (specialised)",
  "Residential care activities",
  "Residential care activities (specialised)",
  "Retail trade, except of motor vehicles and motorcycles",
  "Retail trade, except of motor vehicles and motorcycles (specialised)",
  "Scientific research and development",
  "Scientific research and development (specialised)",
  "Security and investigation activities",
  "Security and investigation activities (specialised)",
  "Seed processing for propagation",
  "Seed processing for propagation (specialised)",
  "Services to buildings and landscape activities",
  "Services to buildings and landscape activities (specialised)",
  "Sewerage",
  "Sewerage (specialised)",
  "Silviculture and other forestry activities",
  "Silviculture and other forestry activities (specialised)",
  "Social work activities without accommodation",
  "Social work activities without accommodation (specialised)",
  "Specialised construction activities",
  "Specialised construction activities (specialised)",
  "Sports activities and amusement and recreation activities",
  "Sports activities and amusement and recreation activities (specialised)",
  "Steam and air conditioning supply",
  "Steam and air conditioning supply (specialised)",
  "Support activities for animal production",
  "Support activities for animal production (specialised)",
  "Support activities for crop production",
  "Support activities for crop production (specialised)",
  "Support activities for petroleum and natural gas extraction",
  "Support activities for petroleum and natural gas extraction (specialised)",
  "Support services to forestry",
  "Support services to forestry (specialised)",
  "Telecommunications",
  "Telecommunications (specialised)",
  "Travel agency, tour operator and other reservation service activities",
  "Travel agency, tour operator and other reservation service activities (specialised)",
  "Undifferentiated goods- and services-producing activities of households for own use",
  "Undifferentiated goods- and services-producing activities of households for own use (specialised)",
  "Veterinary activities",
  "Veterinary activities (specialised)",
  "Warehousing and support activities for transportation",
  "Warehousing and support activities for transportation (specialised)",
  "Waste collection",
  "Waste collection (specialised)",
  "Waste treatment and disposal",
  "Waste treatment and disposal (specialised)",
  "Water collection, treatment and supply",
  "Water collection, treatment and supply (specialised)",
  "Water transport",
  "Water transport (specialised)",
  "Wholesale and retail trade and repair of motor vehicles and motorcycles",
  "Wholesale and retail trade and repair of motor vehicles and motorcycles (specialised)",
  "Wholesale trade, except of motor vehicles and motorcycles",
  "Wholesale trade, except of motor vehicles and motorcycles (specialised)",
];

export const occupationOptions = [
  "Accountant",
  "Accounting Assistant",
  "Actor",
  "Administrative Assistant",
  "Administrator",
  "Animator",
  "App Developer",
  "Architect",
  "Art Director",
  "Artist",
  "Athlete",
  "Auditor",
  "Backend Developer",
  "Barrister",
  "Barista",
  "Bartender",
  "Biochemist",
  "Biologist",
  "Biomedical Scientist",
  "Blockchain Developer",
  "Blogger",
  "Bookkeeper",
  "Builder",
  "Business Analyst",
  "Butcher",
  "Bus Driver",
  "Cab Driver",
  "Cameraman",
  "Camera Operator",
  "Care Assistant",
  "Carpenter",
  "Cashier",
  "Chemical Engineer",
  "Chemist",
  "Chef",
  "Civil Engineer",
  "Civil Servant",
  "Cloud Engineer",
  "Coach",
  "College Lecturer",
  "Composer",
  "Company Secretary",
  "Computer Programmer",
  "Concierge",
  "Consultant",
  "Copywriter",
  "Court Clerk",
  "Courier",
  "Court Clerk",
  "Creative, arts and entertainment",
  "Cyber Security Analyst",
  "Data Analyst",
  "Data Engineer",
  "Data Entry Clerk",
  "Data Scientist",
  "Database Administrator",
  "Decorator",
  "Delivery Driver",
  "Dental Nurse",
  "Dentist",
  "DevOps Engineer",
  "Doctor",
  "Editor",
  "Electrical Engineer",
  "Electrician",
  "Environmental Scientist",
  "Entrepreneur",
  "Event Planner",
  "Executive Assistant",
  "Fashion Designer",
  "Film Director",
  "Financial Advisor",
  "Finance Manager",
  "Firefighter",
  "Fisherman",
  "Fitness Instructor",
  "Floor Fitter",
  "Forest Ranger",
  "Forklift Operator",
  "Freelancer",
  "Front End Developer",
  "Full Stack Developer",
  "Fundraiser",
  "Game Designer",
  "Game Developer",
  "Gardener",
  "Geologist",
  "Graphic Designer",
  "Greenkeeper",
  "Groundskeeper",
  "GP",
  "Gym Manager",
  "HGV Driver",
  "Healthcare Assistant",
  "Horticulturist",
  "Hospital Porter",
  "Hotel Manager",
  "Housekeeper",
  "Illustrator",
  "Immigration Officer",
  "Information Service Activities",
  "Investor",
  "IT Consultant",
  "IT Manager",
  "Journalist",
  "Judge",
  "Kitchen Assistant",
  "Lab Technician",
  "Landscape Gardener",
  "Labourer",
  "Lawyer",
  "Legal Assistant",
  "Legal Secretary",
  "Lifeguard",
  "Logistics Coordinator",
  "Makeup Artist",
  "Management Consultant",
  "Marine Biologist",
  "Marketing Executive",
  "Marketing Manager",
  "Mechanical Engineer",
  "Medical Laboratory Assistant",
  "Medical Secretary",
  "Microbiologist",
  "Midwife",
  "Musician",
  "Network Engineer",
  "Nurse",
  "Nursery Assistant",
  "Occupational Therapist",
  "Office Manager",
  "Optician",
  "Operations Manager",
  "Paramedic",
  "Painter",
  "Paralegal",
  "Payroll Clerk",
  "Personal Trainer",
  "Pharmacist",
  "Pharmacy Technician",
  "Photographer",
  "Physiotherapist",
  "Pilot",
  "Plasterer",
  "Plumber",
  "Police Officer",
  "PR Manager",
  "Primary School Teacher",
  "Probation Officer",
  "Professor",
  "Programmer",
  "Project Manager",
  "Radiographer",
  "Real Estate Agent",
  "Receptionist",
  "Retail Assistant",
  "Retail Manager",
  "Research Scientist",
  "Restaurant Manager",
  "Retired",
  "Roofer",
  "Sales Assistant",
  "Sales Manager",
  "Scaffolder",
  "School Administrator",
  "Secondary School Teacher",
  "Secretary",
  "Security Officer",
  "Self Employed",
  "Senior Manager",
  "Service Manager",
  "Shop Assistant",
  "Site Manager",
  "Social Media Manager",
  "Software Engineer",
  "Solicitor",
  "Special Needs Teacher",
  "Sports Therapist",
  "Store Manager",
  "Structural Engineer",
  "Student",
  "Surgeon",
  "Surveyor",
  "System Administrator",
  "Tax Advisor",
  "Taxi Driver",
  "Teaching Assistant",
  "Team Leader",
  "Technical Support Specialist",
  "Telecommunications",
  "Tiler",
  "Tour Guide",
  "Train Conductor",
  "Train Driver",
  "Transport Manager",
  "Travel Agent",
  "Treasurer",
  "Tree Surgeon",
  "Tutor",
  "UI Designer",
  "Unemployed",
  "UX Designer",
  "Video Editor",
  "Veterinary Nurse",
  "Veterinary Surgeon",
  "Waiter",
  "Waitress",
  "Warehouse Operative",
  "Web Designer",
  "Web Developer",
  "Welder",
  "Writer",
];
