export const carUsageOptions = [
  {
    title: "Social use only",
    description:
      "Personal use such as shopping or visiting friends and family.",
  },
  {
    title: "Social and commuting",
    description:
      "Personal use and driving to and from a single place of work or study.",
  },
  {
    title: "Social, commuting and business",
    description:
      "You drive to various locations for work. You can also add other drivers who use this car for business.",
  },
];

export const otherVehiclesOptions = [
  "Own another car or van",
  "Have use of another car",
  "Company car (including personal use)",
  "Company car (excluding personal use)",
];

export const additionalQualificationsOptions = [
  "AA Proficiency",
  "Institute of Advanced Motorists",
  "Pass Plus",
];

export const monthOptions = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const yearOptions = Array.from({ length: 50 }, (_, i) => {
  const year = new Date().getFullYear() - i;
  return year.toString();
});

export const licenseHeldOptions = [
  "0-1 years",
  "2 years",
  "3 years",
  "4 years",
  "5 years",
  "6 years",
  "7 years",
  "8 years",
  "9 years",
  "10 years",
  "11 years",
  "12 years",
  "13 years",
  "14 years",
  "15+ years",
];

export const ncbOptions = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "15+",
];

export const keepingCarDuringNightOptions = [
  "Drive",
  "Street outside home",
  "Locked garage",
  "Street away from home",
  "Public car park",
  "Work car park",
  "Private property",
];

export const keepingCarDuringDayOptions = [
  "At home",
  "Office or factory car park",
  "Open public car park",
  "Secure public car park",
  "Street away from home",
];
export const employmentStatusOptions = [
  "Self-Employed",
  "Employed",
  "Unemployed",
  "Retired",
  "Student",
];

export const voluntaryExcessOptions = [
  "£0",
  "£100",
  "£250",
  "£500",
  "£750",
  "£1000",
];
export const occupationOptions = [
  "Accountant",
  "Accounting Assistant",
  "Administrative Assistant",
  "Administrator",
  "Auditor",
  "Bookkeeper",
  "Business Analyst",
  "Chief Executive",
  "Company Secretary",
  "Data Entry Clerk",
  "Executive Assistant",
  "Finance Manager",
  "Financial Advisor",
  "Office Manager",
  "Operations Manager",
  "Payroll Clerk",
  "Project Manager",
  "Receptionist",
  "Secretary",
  "Tax Advisor",
  "Treasurer",
  "App Developer",
  "Backend Developer",
  "Blockchain Developer",
  "Cloud Engineer",
  "Computer Programmer",
  "Cyber Security Analyst",
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
  "Database Administrator",
  "DevOps Engineer",
  "Front End Developer",
  "Full Stack Developer",
  "Game Designer",
  "Game Developer",
  "IT Consultant",
  "IT Manager",
  "Network Engineer",
  "Software Engineer",
  "System Administrator",
  "Technical Support Specialist",
  "UX Designer",
  "UI Designer",
  "Web Developer",
  "Web Designer",
  "Care Assistant",
  "Dental Nurse",
  "Dentist",
  "Doctor",
  "GP",
  "Healthcare Assistant",
  "Hospital Porter",
  "Medical Laboratory Assistant",
  "Medical Secretary",
  "Midwife",
  "Nurse",
  "Occupational Therapist",
  "Optician",
  "Paramedic",
  "Pharmacist",
  "Pharmacy Technician",
  "Physiotherapist",
  "Radiographer",
  "Surgeon",
  "Veterinary Nurse",
  "Veterinary Surgeon",
  "Academic Researcher",
  "College Lecturer",
  "Nursery Assistant",
  "Primary School Teacher",
  "Professor",
  "School Administrator",
  "Secondary School Teacher",
  "Special Needs Teacher",
  "Teaching Assistant",
  "Tutor",
  "Bricklayer",
  "Builder",
  "Carpenter",
  "Decorator",
  "Electrician",
  "Floor Fitter",
  "Joiner",
  "Labourer",
  "Painter",
  "Plasterer",
  "Plumber",
  "Roofer",
  "Scaffolder",
  "Site Manager",
  "Surveyor",
  "Tiler",
  "Welder",
  "Barista",
  "Butcher",
  "Cashier",
  "Customer Service Advisor",
  "Customer Support Agent",
  "Delivery Driver",
  "Retail Assistant",
  "Retail Manager",
  "Sales Assistant",
  "Shop Assistant",
  "Store Manager",
  "Supermarket Assistant",
  "Warehouse Operative",
  "Bus Driver",
  "Cab Driver",
  "Courier",
  "Forklift Operator",
  "HGV Driver",
  "Logistics Coordinator",
  "Pilot",
  "Taxi Driver",
  "Train Conductor",
  "Train Driver",
  "Transport Manager",
  "Actor",
  "Animator",
  "Art Director",
  "Artist",
  "Blogger",
  "Camera Operator",
  "Composer",
  "Copywriter",
  "Editor",
  "Fashion Designer",
  "Film Director",
  "Graphic Designer",
  "Illustrator",
  "Journalist",
  "Marketing Executive",
  "Marketing Manager",
  "Musician",
  "Photographer",
  "PR Manager",
  "Social Media Manager",
  "Video Editor",
  "Writer",
  "Barrister",
  "Civil Servant",
  "Court Clerk",
  "Firefighter",
  "Immigration Officer",
  "Judge",
  "Lawyer",
  "Legal Assistant",
  "Legal Secretary",
  "Paralegal",
  "Police Officer",
  "Probation Officer",
  "Solicitor",
  "Bar Manager",
  "Bartender",
  "Chef",
  "Concierge",
  "Event Planner",
  "Hotel Manager",
  "Housekeeper",
  "Kitchen Assistant",
  "Restaurant Manager",
  "Tour Guide",
  "Travel Agent",
  "Waiter",
  "Waitress",
  "Architect",
  "Biochemist",
  "Biologist",
  "Biomedical Scientist",
  "Chemical Engineer",
  "Chemist",
  "Civil Engineer",
  "Electrical Engineer",
  "Environmental Scientist",
  "Geologist",
  "Lab Technician",
  "Marine Biologist",
  "Mechanical Engineer",
  "Microbiologist",
  "Physicist",
  "Research Scientist",
  "Structural Engineer",
  "Agricultural Worker",
  "Farm Manager",
  "Farmer",
  "Fisherman",
  "Forest Ranger",
  "Gardener",
  "Greenkeeper",
  "Groundskeeper",
  "Horticulturist",
  "Landscape Gardener",
  "Tree Surgeon",
  "Athlete",
  "Coach",
  "Fitness Instructor",
  "Gym Manager",
  "Lifeguard",
  "Personal Trainer",
  "Sports Therapist",
  "Consultant",
  "Entrepreneur",
  "Freelancer",
  "Investor",
  "Self Employed",
  "Student",
  "Retired",
  "Unemployed",
];
